### ISSUE TITLE
Autocomplete / Token bug

### ISSUE THREAD

**Issue by ariestav** [revolunet/sublimetext-markdown-preview#382] opened 2017-03-03 03:39 UTC
I wrote a short entry of [a problem I was having with Sublime Text 3 on StackOverflow](http://stackoverflow.com/questions/42566449/avoid-auto-period-character-after-quick-type-space-in-sublime-text-3).  I thought to reference it here.  When I removed this package from Sublime the auto-addition of a period character problem went away.

**Comment by facelessuser** [comment] 2017-03-04 05:59
This plugin doesn't add any auto complete features.  It doesn't do anything unless you manually invoke the preview command.  I believe you have incorrectly identified this plugin as the responsible plugin.

**Comment by facelessuser** [comment] 2017-03-05 04:59
I'm closing this as there is no evidence that the described issue is caused by this plugin.  Feel free to reopen if more substantial evidence is discovered that can implicate this plugin.

**Closed by facelessuser** 2017-03-05 04:59 UTC
