### ISSUE TITLE
Unable to find target command: markdown_build

### ISSUE THREAD

**Issue by Albinutte** [revolunet/sublimetext-markdown-preview#306] opened 2015-12-06 20:00 UTC
Everything seemed to work great just yesterday, but now I can't even build html with the following error: 
`Unable to find target command: markdown_build`

I tried to reinstall the package / sublime, but it didn't do the trick. What could have possibly gone wrong? Any help would be appreciated.

**Comment by facelessuser** [comment] 2015-12-07 18:36
Please look at console and report errors here if any.  I will take a look tonight.  It was a fairly big update internally.

**Comment by facelessuser** [comment] 2015-12-07 18:37
Please also provide as much detail as you can, system, ST version etc.

**Comment by facelessuser** [comment] 2015-12-07 18:43
On ST3 it is working for me.  A restart was required after the update.

**Comment by facelessuser** [comment] 2015-12-07 21:10
Most likely related to #306

**Comment by facelessuser** [comment] 2015-12-07 21:11
I meant #307

**Comment by facelessuser** [comment] 2015-12-07 21:18
Closed duplicate of #307.

**Closed** 2015-12-07 21:18 UTC
Labels: duplicate
