### ISSUE TITLE
Error: github API responded in an unfashion way :/

### ISSUE THREAD

**Issue by ahmetalpbalkan** [revolunet/sublimetext-markdown-preview#292] opened 2015-07-29 07:54 UTC
When I try to preview I get a pop-up error in Sublime saying

    github API responded in an unfashion way :/

and get this browser page:

> ![image](https://cloud.githubusercontent.com/assets/159209/8952493/4bbe02e6-358c-11e5-93ec-c271598cb15a.png)

**Comment by unitof** [comment] 2015-07-30 22:06
Any chance your Markdown syntax is bad? Could you paste it here in a codeblock?

**Comment by facelessuser** [comment] 2015-07-31 06:15
I would guess it was bad markdown syntax as well, but without seeing any example, it is tough to tell.

**Comment by howar31** [comment] 2015-08-09 18:41
Having the same problem.  The plugin cannot convert any markdown file.  Included the Markdown Cheat Sheet in plugin.

**Comment by facelessuser** [comment] 2015-08-09 19:00
I just used this plugin over the weekend using the GitHub API.  Are there any other errors in Sublime's console?  Without more info to help us actually reproduce this, I am afraid no one can help.  Maybe GitHub was just having issues with their API on their end?

**Comment by facelessuser** [comment] 2015-08-09 19:01
You posted before I did.  Did you read the readme?  It talks about the rate limit and what you need to set up.

**Comment by howar31** [comment] 2015-08-09 19:11
@facelessuser oh...god...... I'm so sorry....

I read the readme and set up the token.  And it's now working like a charm and everything goes smooth and well!

Sorry for my fault and thanks for your quickly reply and the awesome plugin! :smile:

**Comment by facelessuser** [comment] 2015-08-09 21:23
Cool.  That explains the issue.  I imagine that was the original posters problem as well.  I will go ahead and close the issue then.  It can be reopened if the original poster is having a different issue and they provide more info.

**Closed by facelessuser** 2015-08-09 21:23 UTC

**Comment by ExplodingCabbage** [comment] 2015-11-06 13:24
FYI, this wonderfully confusing and ungrammatical error message made it into [today's Daily WTF](http://thedailywtf.com/articles/in-memoriam). Congratulations!

It looks like it's been removed from the codebase recently, though?

**Comment by revolunet** [comment] 2015-11-06 13:28
haha awesome, achievement unlocked !

My Frenglish hurts :)

**Comment by SEAPUNK** [comment] 2015-11-24 17:55
I'm getting the same issue, but I have no idea where to set the token. What do I need to do for GFM markdown API requests to be authenticated with my newly generated token?

**Comment by saagarjha** [comment] 2016-02-23 23:00
@SEAPUNK Kinda late, but since I had the same issue I thought I'd share it here. First you need to make an OAuth key in Github, go to your account settings, then "Personal Access Tokens" [here](https://github.com/settings/tokens). Click "Generate new token", name it something descriptive (like "Markdown preview"), and click generate. Once you have the key, copy it to your clipboard (don't share it!), and go to Sublime Text. Open the Markdown Preview User Settings, and add the `"github_oauth_token": "[your token you copied here]"` token. If it's empty, then paste this:  
```
 {
    "github_oauth_token": "[your token you copied here]"
}
```

**Comment by SEAPUNK** [comment] 2016-02-23 23:02
@saagarjha Yeah, I was able to figure it out, but thanks for the comment either way!

**Comment by ghwokai** [comment] 2016-03-07 02:14
@saagarjha thanks a lot!It worked.

**Comment by dogancelik** [comment] 2016-03-14 16:41
This error is not very helpful to debug the problem:

```
error: github API responded in an unfriendly way :/
```

It would be much better, if plugin returned the error message from Github instead.

**Comment by hypergig** [comment] 2016-05-09 13:32
I needed to ditch the squares:

```
{
  "github_oauth_token": "your token you copied here"
}

**Comment by saagarjha** [comment] 2016-07-15 00:27
@hypergig I've updated it to make it more clear.

**Comment by thulioph** [comment] 2016-09-02 18:09
+1 👍

**Comment by reyronald** [comment] 2016-10-20 13:56
Guys, I ran into the exact same issue and had to Google my way around and inspect the source code to be able to figure out what was going on. A regular user shouldn't have to do this! Specially when it's so easy to identify this case from the API's response.

I submitted a pull request to display a more friendly message for this particular scenario, [please take a look at it here.](https://github.com/revolunet/sublimetext-markdown-preview/pull/366)

Basically this is what would be displayed now: 

> It seems like you have exceeded GitHub's API rate limit.

> To continue using GitHub's markdown format with this package, log in to GitHub, then go to Settings > Personal access tokens > Generate new token, copy the token's value, and paste it in this package's user settings under the key  'github_oauth_token'. Example:

> {
	"github_oauth_token": "xxxx....""
}

> GitHub's original response: (HTTP Status Code 403) "API rate limit exceeded for IPADDRESS (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"

![markdownpreviewgithubapierror](https://cloud.githubusercontent.com/assets/7514993/19562653/1a7bae50-96ab-11e6-96a4-ebf5a5ee01a9.PNG)

Let me know if you have any suggestions over there.

@saagarjha @dogancelik @hypergig

**Comment by btforsythe** [comment] 2017-02-12 20:13
Thanks for the save @reyronald.

Why is that PR still open?

**Comment by facelessuser** [comment] 2017-02-12 20:19
Because the few collaborators on this repo haven't had much time to spend on the project.  That pull hasn't been reviewed.

Just glancing at it, those carriage returns should get removed from the messages.

**Comment by reyronald** [comment] 2017-02-17 18:32
@btforsythe You're welcome!

@facelessuser Thanks for the suggestion, and yeah, I'm still waiting for any collaborator to review/approve the PR. I'm still active on GitHub so as soon as I get any notification on the matter I can commit whatever changes necessary.

**Comment by facelessuser** [comment] 2017-02-17 18:49
@reyronald, l take a look this weekend, so we can get this merged.
